### ISSUE TITLE
StoragePath and CKAN path are different

### ISSUE THREAD

**Issue by miguelangelch** [keitaroinc/ckan-helm#69]
The deployment manifest, by default (at least in the master branch) is using the following volumeMounts code:

```
          volumeMounts:
          - name: "ckan"
            mountPath: {{ .Values.ckan.storagePath }}
            readOnly: false
```

Where, by default, storagePath value is ` "/var/lib/ckan/default"`

However, once I deploy the container, when I shell into it, that folder does not exists:

![image](https://user-images.githubusercontent.com/12670461/224969533-14da71c9-1f18-4782-babf-56516b0947e5.png)

By default, when I join to the container, the default path with the config files is: `/srv/app`

**Where can I found the paths related uploads, resources, plugins and base installation?** Are in the same folder  `/srv/app` ?

In a VM installation the folders are:

- /var/lib/ckan = Uploads, resources and plugins
- /usr/lib/ckan = Base installation

However, in the container, those paths don't exist.
