### ISSUE TITLE
Sharing volume (VolumeMount) /srv/app failed

### ISSUE THREAD

**Issue by miguelangelch** [keitaroinc/ckan-helm#70]
I want to share in a PVC the folder /srv/app to be able to migrate plugins, resources, datsources from another CKAN.

What I added in the CKAN deployment.yaml template:

```
      volumes:
        - name: "ckan"
          persistentVolumeClaim:
            claimName: "ckan"
        - name: "ckan2"
          persistentVolumeClaim:
            claimName: "ckan2"
```
Related CKAN container:

```
          volumeMounts:
          - name: "ckan"
            mountPath: {{ .Values.ckan.storagePath }}
            readOnly: false
          - name: "ckan2"
            mountPath: "/srv/app"
            readOnly: false

```

However, starting up the pod, gets a **CrashLoopBackOff**:

![image](https://user-images.githubusercontent.com/12670461/225648435-e4667255-9354-4acc-8577-9028bfa3bb77.png)

As far as I understood, it follow these steps:

 1. Run the init container (busy box) to set 92:92 (CKAN user) owners to the /var/lib/ckan folder.
 2. Run the CKAN container (keitaro/ckan) which in the Dockerfile, copy all folders from /srv/app to the container with the same path:

![image](https://user-images.githubusercontent.com/12670461/225649075-d5f75b4c-7083-4109-a163-05bc6c4c7f1c.png)

So I don't understand why it says the file in the folder /srv/app doesn't not exists... Is there any way to sahre the /srv/app folder to be able to migrate the resources (plugins), datastore and maybe the config.ini?
