### ISSUE TITLE
init- & test-connection container image registries cannot be configured

### ISSUE THREAD

**Issue by JoooostB** [keitaroinc/ckan-helm#76]
Some environment (like ours) do not allow for pulling remote images, and thus the install tends to break on the `busybox:latest` container used in both the init-container from CKAN and the test-connection container from the Helm template.
It'd be great if both occurrences of the `busybox` image can be configured.

## Proposal:
Add some fields to the `values.yaml` which allows for configuring the `busybox` registries:
```yaml
...
image:
  repository: keitaro/ckan
  tag: 2.9.4
  pullPolicy: IfNotPresent
  testConnection:
    repository: harbor.containers.wurnet.nl/library/busybox
    tag: latest
    pullPolicy: IfNotPresent
  initContainer:
    repository: harbor.containers.wurnet.nl/library/busybox
    tag: latest
    pullPolicy: IfNotPresent  
...
```
